version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    orderdb:
        image: mcr.microsoft.com/mssql/server

    rabbitmq:
        image: rabbitmq:3-management-alpine

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Microservices/CatalogMicroservice/Catalog.API/Dockerfile

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: src/Microservices/BasketMicroservice/Basket.API/Dockerfile

    order.api:
        image: ${DOCKER_REGISTRY-}orderapi
        build:
            context: .
            dockerfile: src/Microservices/OrderMicroservice/Order.API/Dockerfile

    ocelotapigateway:
        image: ${DOCKER_REGISTRY-}ocelotapigateway
        build:
            context: .
            dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile

